name: Code Quality and Tests 

on: [push] 

jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run linter test
        run: npm run lint
      - name: Unit Test
        run: npm test ./admin/tests/unit.test.js
      - name: E2E Test For Homepage
        run: npm run e2ehometest
      - name: Generate JSDoc
        run: npm run docs
